export const RANDOM_QUIZ_TOPICS = [
  'World History',
  'Ancient Civilizations',
  'Famous Explorers',
  'Geography of Europe',
  'African Wildlife',
  'Human Anatomy',
  'Famous Inventions',
  'Space Exploration',
  'Greek Mythology',
  'The Solar System',
  'Modern Art Movements',
  'Renaissance Art',
  'Famous Battles in History',
  'World War I',
  'World War II',
  'Political Systems',
  'Physics Fundamentals',
  'Chemistry Elements',
  'Nobel Prize Winners',
  'Famous Authors',
  'Shakespeare Plays',
  'Science Fiction Literature',
  'French Revolution',
  'World Capitals',
  'Mountain Ranges',
  'Deserts of the World',
  'Marine Biology',
  'Human Psychology',
  'Mathematical Theorems',
  'World Religions',
  'Philosophy of Ethics',
  'Famous Philosophers',
  'Dinosaurs',
  'Evolutionary Biology',
  'World Economy',
  'Famous Scientists',
  'Musical Instruments',
  'Classical Music Composers',
  'Pop Culture Icons',
  'Famous Films',
  'Oscar-Winning Movies',
  'Jazz History',
  'Global Climate Change',
  'Renewable Energy',
  'Medical Discoveries',
  'World War II Leaders',
  'Medieval Europe',
  'World Empires',
  'Historical Monuments',
  'Ancient Greece',
  'Ancient Egypt',
  'Roman Empire',
  'Cultural Festivals',
  'Olympic Games History',
  'Computer Science Basics',
  'Programming Languages',
  'Cybersecurity',
  'Social Media Platforms',
  'Artificial Intelligence',
  'Robotics',
  'Spacecraft and Satellites',
  'Astronomy Constellations',
  'Physics of Sound',
  'Quantum Mechanics',
  'Thermodynamics',
  'Famous Mathematicians',
  'World Geography',
  'South American Countries',
  'North American Landmarks',
  'Asian Countries and Capitals',
  'Middle Eastern Conflicts',
  'Global Human Rights',
  'International Organizations',
  'UN Sustainable Goals',
  'Famous Architects',
  'Art History Movements',
  'Cultural Anthropology',
  'Sociology Theories',
  'Psychological Disorders',
  'Cognitive Behavioral Therapy',
  'Plant Biology',
  'Marine Ecosystems',
  'Endangered Species',
  'Oceanography',
  'Meteorology',
  'Volcanoes and Earthquakes',
  'Plate Tectonics',
  'Rivers and Lakes',
  'Deserts and Oases',
  'Bird Species',
  'Insects of the World',
  'Human Skeleton',
  'Brain and Nervous System',
  'Genetics',
  'Famous Political Leaders',
  'Colonialism',
  'Human Rights Activists',
  'Global Environmental Issues',
  'History of Space Travel',
  'Famous Castles',
  'Space Telescopes',
  'History of the Internet',
  'World Architecture',
  'Famous Discoveries in Science',
  'Sharks and Marine Predators',
  'The Renaissance Period',
  'Medieval Architecture',
  'Ancient Roman Engineering',
  'Geography of South America',
  'Countries of the Middle East',
  'Nuclear Physics',
  'The Periodic Table',
  'Organic Chemistry',
  'Botanical Gardens',
  'Human Evolution',
  'Fossils and Paleontology',
  'Artificial Satellites',
  'Space Missions to Mars',
  'History of Space Stations',
  'Physics of Black Holes',
  'Genetic Engineering',
  'Artificial Intelligence Ethics',
  'Cryptocurrencies',
  'Blockchain Technology',
  'Famous Video Games',
  'Computer Programming',
  'Mobile Application Development',
  'Cloud Computing',
  'History of Operating Systems',
  'History of the Cold War',
  'The Vietnam War',
  'The Gulf War',
  'Famous Speeches in History',
  'History of Democracy',
  'International Space Station',
  'Famous Kings and Queens',
  'Presidents of the United States',
  'Prime Ministers of the UK',
  'Famous Historical Treaties',
  'Economic Theories',
  'Stock Market Crashes',
  'Cryptography',
  'Cybercrime',
  'Internet Safety',
  'History of Robotics',
  '3D Printing',
  'Augmented Reality',
  'Virtual Reality',
  'Evolution of the Smartphone',
  'Electric Cars',
  'Famous Bridges',
  'Skyscrapers Around the World',
  'World Wonders',
  'Historical Inventions',
  'The Industrial Revolution',
  'The Information Age',
  'The Space Age',
  'Molecular Biology',
  'DNA and Genes',
  'Biotechnology',
  'Famous Chemists',
  'World Rivers',
  'Lakes and Reservoirs',
  'World Mountain Peaks',
  'Geology',
  'History of Medicine',
  'Famous Diseases and Epidemics',
  'Vaccinations',
  'Space Agencies Around the World',
  'Astronomy Discoveries',
  'Exoplanets',
  'History of the Moon Landing',
  'History of Astronomy',
  'Famous Museums',
  'Art Collectors',
  'Gothic Architecture',
  'Post-Impressionism',
  'Baroque Art',
  'Modern Architecture',
  'Famous Explorers of the Seas',
  'Natural Disasters',
  'Environmental Activism',
  'World Languages',
  'Biodiversity',
  'Human Impact on the Environment',
  'Climate Change Policies',
  'Sustainable Development',
  'Energy Conservation',
  'Famous Spacecrafts',
  'History of Aviation',
  'World War I Leaders',
  'Medieval Kings',
  'Famous Female Scientists',
  "History of Women's Rights",
  'Political Ideologies',
  'Socialism vs Capitalism',
  'World War II Battles',
  'History of Television',
  'The Film Industry',
  'History of Comic Books',
  'Famous Book Awards',
  'Hollywood Studios',
  'History of Photography',
  'Cinematography Techniques',
];
