name: Angular Unit Tests

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install --force

      - name: Run Unit Tests
        run: npm run test:prod
